---
deployment:
  tasks:
    - export DEPLOYPATH=/home/langitte/public_html/wp-content/themes/xampp.repo
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R inc $DEPLOYPATH
    - /bin/cp -R template-parts $DEPLOYPATH
    - /bin/cp 404.php $DEPLOYPATH
    - /bin/cp archive.php $DEPLOYPATH
    - /bin/cp comments.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp front-page.php $DEPLOYPATH
    - /bin/cp functions.php $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp page.php $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp readme.txt $DEPLOYPATH
    - /bin/cp rtl.css $DEPLOYPATH
    - /bin/cp screenshot.png $DEPLOYPATH
    - /bin/cp search.php $DEPLOYPATH
    - /bin/cp searchform.php $DEPLOYPATH
    - /bin/cp sidebar.php $DEPLOYPATH
    - /bin/cp single.php $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
